webstats:
  enable: true
  action: "www.somescript.com/dothis.php"
  secret: "abcdef12345"
  position: 0
settings:
  maps_repo: "/home/founders/repo/maps"
  voteTime: 30
  cycleTime: 30
  startTime: 30
database:
  enabled: true
  username: "jj"
  password: "S^yL?dX5@a9L"
  database: "mira"
  hostname: "core.mira.sbs"
  port: 5432